name: Build iOS

on:
  push:
    branches: [ master ] # سيعمل عند كل رفع كود لفرع master كما يظهر في صورتك

jobs:
  build:
    runs-on: macos-14 # استخدام أحدث سيرفر متاح
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build
        run: |
          # سنقوم ببناء المشروع للتأكد من سلامة الكود
          # ملاحظة: إذا كان اسم مشروعك مختلف عن orthodox_app، غيره هنا
          xcodebuild build -scheme orthodox_app -sdk iphonesimulator
